name: Fetch News

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch_news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-bigquery pandas feedparser

    - name: Set GCP Credentials
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > gcp_key.json

    - name: Run News Fetching Script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_key.json
      run: python googRSS.py
