name: Fetch and Upload News

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-bigquery google-auth feedparser pandas

    - name: Set up Google Cloud credentials
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS" > gcp_key.json
        export GOOGLE_APPLICATION_CREDENTIALS="$PWD/gcp_key.json"

    - name: Run News Fetch Script
      run: python googRSS.py
