name: Fetch News Articles

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours

jobs:
  fetch_and_upload_news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-bigquery feedparser pandas

    - name: Prepare GCP credentials
      run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > gcp_key.json

    - name: Set Environment Variable
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp_key.json" >> $GITHUB_ENV

    - name: Run News Fetch Script
      run: python googRSS.py
