name: Fetch NewsAPI Data

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  fetch-newsapi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Google Application Credentials
      env:
        GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

    - name: Run NewsAPI Fetch Script
      run: python newsAPI.py
