name: Run NewsAPI Script

on:
  # Run every 12 hours
  schedule:
    - cron: '0 */12 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  run_news_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pandas google-cloud-bigquery newsapi-python pyarrow

      - name: Create service account key file
        run: |
          cat <<'EOF' > keyfile.json
          ${{ secrets.GCP_CREDENTIALS }}
          EOF

      - name: Run the NewsAPI script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: keyfile.json  # Tell BigQuery to use the key file
        #run: python newsAPI.py #uncoment to run
