name: Run News Script

on:
  # Run on a schedule (adjust the cron schedule as needed)
  schedule:
    - cron: '0 * * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  run_news_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install feedparser pandas google-cloud-bigquery

      - name: Create service account key file
        run: |
          # Use printf to preserve the JSON formatting
          printf '%s' "${{ secrets.GCP_CREDENTIALS }}" > keyfile.json

      - name: Run the news script
        env:
          # Tell the BigQuery client to use this key file automatically
          GOOGLE_APPLICATION_CREDENTIALS: keyfile.json
        run: python googRSS.py
